export const UPDATE_USER = 'UPDATE_USER';

export const RESET_COLLECTION = 'RESET_COLLECTION';
export const SYNC_COLLECTION = 'SYNC_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';

export const PICK_CURRENT = 'PICK_CURRENT';
export const UPDATE_CURRENT = 'UPDATE_CURRENT';
